version: '3.9'

services:
  backend:
    build: pocketbase
    container_name: pocketbase
    volumes:
      - ./docker/pocketbase:/pb/pb_data
    restart: unless-stopped
    ports:
      - 8080:8080
